### ISSUE TITLE
Problem Parsing Dereference

### ISSUE THREAD

**Issue by DavePearce** [Whiley/WhileyCompiler#491]
The following code does not parse correctly:

<pre>
function f(&int x) -> bool:
    return *x == 1
</pre>

The error message is:

<pre>
./test.whiley:2: incomparable operands: &int and int
    return *x == 1
            ^^^^^^
</pre>

However, if you change it to <code>(*x) == 1</code> then it works OK.

**Comment by DavePearce** [comment]
This is now fixed.

**Comment by utting** [comment]
I get the same/similar problem happening with WhileyCompiler 0.6.1 with the following program:

method test():
    &int[] aa = new [1,3,5]
    &int[] bb = new [10,11,12,13]
    *aa[1] = *bb[2]

The last line gives a syntax error, but parses correctly if you write just the left-hand side as (*aa)[1].

It would be nicer if the precedence of * vs [] was the same on the left-hand side and right-hand side of assignments?

**Comment by DavePearce** [comment]
Hey,

Yeh, this is an interesting one.

**Comment by utting** [comment]
I think the problem is with the parsing of the expressions, not the types.
So RFC 0006 will not fix this?

This example still shows the same syntax error on the last line:
method test():
   &(int[]) aa = new [1,3,5]
   &(int[]) bb = new [10,11,12,13]
   *aa[1] = *bb[2]


Experimenting with various brackets, it looks like:
   *aa[1] parses as *(aa[1]) on the left-hand side of an assignment, but
   *aa[1] parses as (*aa)[1] on the right-hand side of an assignment.

**Comment by DavePearce** [comment]
Hey Mark,

No, no --- it's about types specifically!  RFC0001 is about expressions:

https://github.com/Whiley/RFCs/blob/master/text/0001-precedence.md

**Comment by DavePearce** [comment]
**UPDATE:** I also do agree that consistency is an issue and it should at least be consistent!!

**Comment by DavePearce** [comment]
This has been fixed at some point along the way!
